spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # use swagger & css
  application:
    name: user-service

  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/link-library
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # sql 문 포맷
        default_batch_fetch_size: 100  # batch size 설정

  redis:
    host: localhost
    port: 6379
logging.level:
  org.hibernate.SQL: debug # 디버그 모드로 sql 출력

file:
  dir: C:/Users/김진수/link-library/

jwt:
  secret: gsgsefzsefesgazseffzsefgzsgzsfafaesfaesgaseasdgasfasegsegsgasefsegzsegfasefaegaefsefsegasezds

